paths:
  rte_case14_realistic: data/rte_case14_realistic/
  rte_case14_realistic_chronics: data/rte_case14_realistic/chronics/
  medha_imitation: data/medha_imitation_sample/
  tutor_imitation: data/tutor_generated_data/
  processed_tutor_imitation: data/processed_tutor_data/
  action_space: action_space/
  con_matrix_cache: data/auxilary_data_objects/con_matrix_cache.json
  feature_statistics: data/auxilary_data_objects/feature_statistics.json

tutor_generated_data:
  n_chronics: 50
  seed: 1
  
rte_case14_realistic:
  thermal_limits: [1000,1000,1000,1000,1000,1000,1000, 760,450, 760,380,380,760,380,760,380,380,380,2000,2000]
  ts_in_day: 288 #Number of timesteps in a grid2op day
  n_subs: 14
  
training:
  settings:
    train_log_freq: 2000 #How often to log the training set statistics
    val_log_freq: 6000 #How often to evaluate the validation set
    advanced_val_analysis: false
  hyperparams:
    n_epoch: 100
    lr: 3.0E-3
    network_type: heterogenous #Should be 'homogenous' or 'heterogenous'
    N_GNN_layers: 8
    N_node_hidden: 32 #Size of hidden layers in model
    LReLu_neg_slope: 0.1
    batch_size: 64
    label_smoothing_alpha: 0.2 #Controls the extent of label smoothing
    #kaiming_weight_init: false
    weight_init_std: 1
    aggr: add #Aggregation function: should be 'add' or 'mean'
    weight_decay: 0.01
    non_sub_label_weight: 0.1
  constants:
    N_f_gen: 3 #Number of generator features
    N_f_load: 3 #Number of load features
    N_f_endpoint: 6 #Number of endpoint (origin/extremity) features
    estimated_train_size: 18195 #Used for estimating tqdm duration
  wandb:
    #model_name: test_hetero_wdecay
    model_tags: [hetero, hyperparameter_search1]
    project: msc_thesis_gnn_power
    entity: mattholomew
