paths:
  rte_case14_realistic: data/rte_case14_realistic/
  rte_case14_realistic_chronics: data/rte_case14_realistic/chronics/
  medha_imitation: data/medha_imitation_sample/
  tutor_imitation: data/tutor_generated_data/
  processed_tutor_imitation: data/processed_tutor_data/
  action_space: action_space/
  con_matrix_cache: data/auxiliary_data_objects/con_matrix_cache.json
  feature_statistics: data/auxiliary_data_objects/feature_statistics.json
  action_counter: data/auxiliary_data_objects/action_counter.json

tutor_generated_data:
  n_chronics: 50
  seed: 1
  line_idxs_to_consider_N-1: [0, 1, 2, 3, 4, 5, 6, 10, 12, 13, 15, 16, 19] # The indices of the lines to disable
  # for evaluating N-1 scenarios

rte_case14_realistic:
  thermal_limits: [1000,1000,1000,1000,1000,1000,1000, 760,450, 760,380,380,760,380,760,380,380,380,2000,2000]
  ts_in_day: 288 #Number of timesteps in a grid2op day
  n_subs: 14
  sub_info: [3, 6, 4, 6, 5, 6, 3, 2, 5, 3, 3, 3, 4, 3]
  gen_pos_topo_vect: [ 7, 11, 28, 34,  2]
  load_pos_topo_vect: [ 8, 12, 18, 23, 29, 39, 42, 45, 48, 52, 55]
  line_or_pos_topo_vect: [ 0,  1,  4,  5,  6, 10, 15, 24, 25, 26, 35, 36, 41, 47, 51, 16, 17, 22, 31, 38]
  line_ex_pos_topo_vect: [ 3, 19,  9, 13, 20, 14, 21, 43, 46, 49, 40, 53, 44, 50, 54, 30, 37, 27, 33, 32]
  
dataset:
  train_perc: 0.7 #Percentage of the files used in the training set
  val_perc: 0.15 #Percentage of the files validation set
  #Remainder is used in the test set
  
training:
  settings:
    train_log_freq: 2000 #How often to log the training set statistics
    val_log_freq: 18000 #How often to evaluate the validation set
    advanced_val_analysis: true
  hyperparams:
    model_type: GCN  #Should be GCN or FCNN
    n_epoch: 100
    lr: 1.5E-3
    N_node_hidden: 120 #Size of hidden layers in model
    LReLu_neg_slope: 0.1
    batch_size: 32
    label_smoothing_alpha: 0 #Controls the extent of label smoothing
    weight_init_std: 3
    weight_decay: 3.0E-4
    non_sub_label_weight: 0.1
    early_stopping_patience: 50 #stop training when max. val. macro accuracy
    #valid hasn't improved
    action_frequency_threshold: 0 #min. frequency of an action in the
    #dataset in order to be used during training. Can be used to filter 
    #infrequent actions
    class_weights:
      max_adapt_weight: 10
      min_weight_zero: 10
  constants:
    estimated_train_size: 36497 #Used for estimating tqdm duration
  GCN:
    hyperparams:
      network_type: heterogeneous #Should be a str as defined in training.models.GCN.NetworkType
      N_GCN_layers: 8
      aggr: add #Aggregation function: should be 'add' or 'mean'
    constants:
      N_f_gen: 3 #Number of generator features
      N_f_load: 3 #Number of load features
      N_f_endpoint: 6 #Number of endpoint (origin/extremity) features
  FCNN:
    hyperparams:
      N_layers: 4
    constants:
      size_in: 344
      size_out: 56
  wandb:
    model_name: test #GCN_test_diff_label_weights
    model_tags: [test] #[GCN, different_label_weights]
    group: null
    project: msc_thesis_gnn_power
    entity: mattholomew
    mode: online # disabled
